package names

// All category names
const (
	Housewares    = "housewares"
	Miscellaneous = "miscellaneous"
	WallMounted   = "wall-mounted"
	Wallpaper     = "wallpaper"
	Floors        = "floors"
	Rugs          = "rugs"
	Photos        = "photos"
	Posters       = "posters"
	Tools         = "tools"
	Fencing       = "fencing"
	Tops          = "tops"
	Bottoms       = "bottoms"
	DressUp       = "dress-up"
	Headwear      = "headwear"
	Accessories   = "accessories"
	Socks         = "socks"
	Shoes         = "shoes"
	Bags          = "bags"
	Umbrellas     = "umbrellas"
	ClothingOther = "clothing other"
	Music         = "music"
	Insects       = "insects"
	Fish          = "fish"
	SeaCreatures  = "sea creatures"
	Fossils       = "fossils"
	Art           = "art"
	Recipes       = "recipes"
	Other         = "other"
	Construction  = "construction"
	Achievements  = "achievements"
	Villagers     = "villagers"
	SpecialNPCs   = "special npcs"
	Reactions     = "reactions"
	MessageCards  = "message cards"
)
