definitions:
  categories.CategoryItem:
    properties:
      catch_difficulty:
        type: string
      catchphrase:
        type: string
      critterpedia_image:
        type: string
      description:
        type: string
      furniture_image:
        type: string
      icon_image:
        type: string
      image:
        type: string
      movement_speed:
        type: string
      name:
        type: string
      nh_availability:
        $ref: '#/definitions/categories.YearlyAvailability'
      number:
        type: integer
      rainy_days:
        type: boolean
      sell:
        type: integer
      sh_availability:
        $ref: '#/definitions/categories.YearlyAvailability'
      shadow:
        type: string
      size:
        type: string
      spawn_rates:
        type: string
      surface:
        type: string
      total_catches_to_unlock:
        type: integer
      unique_id:
        type: string
      vision:
        type: string
      weather:
        type: string
      where_how:
        type: string
    type: object
  categories.YearlyAvailability:
    additionalProperties:
      type: string
    type: object
  main.ErrorResponse:
    properties:
      error:
        example: invalid input
        type: string
      extra:
        additionalProperties: true
        type: object
    type: object
info:
  contact: {}
  description: Animal Crossing data galore
  title: Nookbase
  version: "1.0"
paths:
  /search/{category}:
    get:
      consumes:
      - application/json
      parameters:
      - description: The search query
        in: query
        name: q
        required: true
        type: string
      - description: 'Item category to search through (eg: fish, insects, etc.)'
        in: path
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/categories.CategoryItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Performs a search for items in the given category
      tags:
      - items
  /seasonal/{hemisphere}/{category}:
    get:
      consumes:
      - application/json
      parameters:
      - description: The hemisphere to check availability for
        enum:
        - northern
        - southern
        in: path
        name: hemisphere
        required: true
        type: string
      - description: 'Item category to search through (eg: fish, insects, etc.)'
        in: path
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/categories.CategoryItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Performs a lookup for items that are currently in season for the given
        hemisphere and category
      tags:
      - items
swagger: "2.0"
